Added txOrigin and protocolVersion params to taker requests
0xProject/quote-server pull request #9
Opened 2020-12-07 00:59 UTC by alexkroeger

Added `txOrigin` and `protocolVersion` params.

2020-12-07 19:41 UTC, alexkroeger commented on src/types.ts
> +        protocolVersion?: string;
change to enum--in ('3','4')

2020-12-07 19:41 UTC, alexkroeger commented on src/request_parser.ts
> +            protocolVersion: query.protocolVersion,
default to '3'

2020-12-15 19:08 UTC, PirosB3 requested changes
Just a handful of comments

2020-12-15 19:08 UTC, PirosB3 commented on src/handlers.ts
> +       throw new Error('Response and request protocol versions do not match');
This is perfect, since we are in the web thread here I'm just going to finish things gracefully and return a `501 Not Implemented`

2020-12-15 19:08 UTC, PirosB3 commented on src/request_parser.ts
> +                    throw new Error('v4 request must specify txOrigin');
Since this is a little duplicated code, I'm going to go ahead and refactor this check in it's own statement

2020-12-16 01:19 UTC, alexkroeger commented on test/handlers_test.ts
> +    it('should fail version with an invalid protocol or txOrigin', () => {
this is great!

2020-12-16 01:47 UTC, alexkroeger commented on src/handlers.ts
> +            .json({ errors: ['Server does not support the requested protocol version'] })
This doesn't seem to be the right error message

2020-12-16 01:48 UTC, alexkroeger commented
Should we bump the version?

2020-12-16 01:51 UTC, alexkroeger commented on src/handlers.ts
> +            .json({ errors: ['Server does not support the requested protocol version'] })
I suppose this is fine, it's saying the server doesn't correctly handle the versioned request

2020-12-16 01:53 UTC, PirosB3 commented
Yes we should bump the version!

2020-12-16 01:57 UTC, PirosB3 approved these changes

2020-12-16 02:00 UTC, merged